const notFound = (req, res, next) => {     // This specifically handles error in which the route is very different for eg: /astralis
    const error = new Error(`Not Found - ${req.originalUrl}`);
    res.status(404);
    next(error);
}

const errorHandler = (err, req, res, next) => {              // an error midleware, since sometimes we can have a success response 
    // even for failed status       
    const statusCode = res.statusCode === 200 ? 500 : res.statusCode;
    res.status(statusCode)
    res.json({
        message: err.message, // this error message is generated by express-async-handler
        
        stack: process.env.NODE_ENV === 'production' ? null : err.stack
    })
}

export { notFound, errorHandler }